---
title: "Week 3 - Fundamentals of questionnaire design"
format: html
---

This week, we talk about the basics of questionnaire (or <i>experimental</i>) design. Especially, we will discuss the following concepts through several studies involving language:
- Independent variable(s) and dependent variable(s)
- Within-participants design, between-participants design, and mixed designs
- What "factors" and "levels" are in a factorial design
- Why the need to counterbalance, and how Latin square designs work for that

the discussion will be based on these two following readings: Abbuhl et al. (2014) (from the book Research Methods in Linguistics) and Rogers & Révész (2020) (fron the book the routledge handbook of research methods in applied linguistics)

Help graphic sumary for the students:

[file name: Week3Summary.svg]

We will also learn the technical terms to describe the methodology employed in a questionnaire/experiment, which will be helpful for you when (a) reading academic papers or attending talks and conferences, and (b) writing your own final term paper or other studies. 





