---
title: "Week 2 - What is language, and ethics in linguistic and experimental research"
format: html
---

During Week 2, we will talk about several topics in more details:

- What is language, and <i>where</i> is language? What are the consequences of the answers of these questions when doing linguistic survey?

- What are the ethical (another similar word for 'ethical': <i>respectful</i>) practices to take into consideration when doing linguistic survey (and any other kind of survey)? We will look at real examples that I encountered in the past few years.

- What are the institutional structures for ethic research in Taiwan? Especially, we will focus on the <b>Center for Taiwan Academic Research Ethics Education</b> (in Chinese: 臺灣學術倫理教育資源中心) provided by the Ministry of Education, and I will show you why you should care about it even as undergraduate and graduate students.

Link to the <b>Center for Taiwan Academic Research Ethics Education 臺灣學術倫理教育資源中心: </b> <a href="https://ethics.moe.edu.tw/" target="_blank">https://ethics.moe.edu.tw/</a>

Assignment for next week: For students enrolled in the program (and if you have time): Take the mandatory online ethic classes and pass the examination (about 6 hours). No need to upload the certificate of results. I will provide a sheet on Moodle, and you will just need to check next to your name.
